version: '3.8'

services:
  fast-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fast-mcp-server
    restart: unless-stopped
    # Expose port for mcp-proxy streamable HTTP server
    ports:
      - "8096:8096"
    
    # Environment variables (add as needed)
    environment:
      - NODE_ENV=production
    
    # Volume mounts for development (uncomment for development)
    # volumes:
    #   - ./config:/app/config:ro
    #   - ./dist:/app/dist
    
    # Health check (optional) - check if mcp-proxy is responding
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8096"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service with hot reload
  fast-mcp-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: fast-mcp-dev
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: pnpm run dev
    profiles:
      - dev


