name: "hg-rag"
variables:
  user_query: 
    required: true

request_template:
  URL: https://cognita-ps-backend.ml.tfy-eo.truefoundry.cloud/retrievers/basic-rag/answer
  METHOD: POST
  HEADERS:
    - Content-Type: application/json
  BODY: |
    {
      "collection_name": "hg",
      "query": "{user_query}",
      "model_configuration": {
        "name": "truefoundry/openai-main/gpt-4o-mini",
        "parameters": {
          "temperature": 0.1
        }
      },
      "prompt_template": "You are an AI assistant specialising in information retrieval and analysis.  Answer the following question based only on the given context:\\nContext: {context}  \\nQuestion: {question}",
      "retriever_name": "vectorstore",
      "retriever_config": {
        "search_type": "similarity",
        "search_kwargs": {
          "k": 5
        }
      }
    }

response_parser:
  enabled: true
  fields: ["answer"]
  format: "text"
  fallbackToFullResponse: true

post_processor:
  maxLength: 1500
  truncateAt: "characters"
  preserveFormatting: true